import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import ethers from "ethers"
import { useProvider, useSigner, useContractWrite, useContractRead } from 'wagmi'

let contractAddress = "0x39dd11c243ac4ac250980fa3aea016f73c509f37"
let abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "previousHolder",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "currentHolder",
        "type": "address"
      }
    ],
    "name": "FlagCaptured",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "captureTheFlag",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "currentHolder",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
]

const Home: NextPage = () => {
  const provider = useProvider();

  const { data, isError, isLoading, write } = useContractWrite(
    {
      addressOrName: '0x39dd11c243ac4ac250980fa3aea016f73c509f37',
      contractInterface: abi,
    },
    'captureTheFlag',
    {
      onSuccess(data) {
        console.log('Success', data)
      },
    },
  )
  const signer = useSigner();

  const captureData = useContractRead(
    {
      addressOrName: '0x39dd11c243ac4ac250980fa3aea016f73c509f37',
      contractInterface: abi,
    },
    'currentHolder',
    {
      onSuccess(data) {
        console.log('Success', data)
      },
    },
  )
  
  console.log('Getting Data: ')
  console.log(captureData.data)
  console.log('Capturing Flag:')
  console.log(data)

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{' '}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <button onClick={() => write()} className={styles.card}>
            <h2>Press to sus &rarr; {}</h2>
            <p>Grab the flag while you can.</p>
          </button>

          <a href="https://wagmi.sh" className={styles.card}>
            <h2>wagmi Documentation &rarr;</h2>
            <p>Learn how to interact with Ethereum.</p>
          </a>

          <a
            href="https://github.com/rainbow-me/rainbowkit-examples"
            className={styles.card}
          >
            <h2>RainbowKit Examples &rarr;</h2>
            <p>Discover boilerplate example RainbowKit projects.</p>
          </a>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Next.js Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Next.js Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
